// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62EWymo2h2E2460X6TG96_ffChJW5gWQ',
    appId: '1:481531315929:web:34b4f5a8e0f08f256be0c8',
    messagingSenderId: '481531315929',
    projectId: 'safecrop-c426d',
    authDomain: 'safecrop-c426d.firebaseapp.com',
    storageBucket: 'safecrop-c426d.firebasestorage.app',
    measurementId: 'G-H4Z3ZF4L25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlBviQGxZgx1Hk25b2Yx8par4LiMlbKA',
    appId: '1:481531315929:android:5da163a80613014d6be0c8',
    messagingSenderId: '481531315929',
    projectId: 'safecrop-c426d',
    storageBucket: 'safecrop-c426d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBts_NtAJ5TCBQeC5IlfOs7Jp6sBxLVtok',
    appId: '1:481531315929:ios:a64be769bed3318f6be0c8',
    messagingSenderId: '481531315929',
    projectId: 'safecrop-c426d',
    storageBucket: 'safecrop-c426d.firebasestorage.app',
    iosBundleId: 'com.example.safecrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBts_NtAJ5TCBQeC5IlfOs7Jp6sBxLVtok',
    appId: '1:481531315929:ios:a64be769bed3318f6be0c8',
    messagingSenderId: '481531315929',
    projectId: 'safecrop-c426d',
    storageBucket: 'safecrop-c426d.firebasestorage.app',
    iosBundleId: 'com.example.safecrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62EWymo2h2E2460X6TG96_ffChJW5gWQ',
    appId: '1:481531315929:web:eb19766609eee6016be0c8',
    messagingSenderId: '481531315929',
    projectId: 'safecrop-c426d',
    authDomain: 'safecrop-c426d.firebaseapp.com',
    storageBucket: 'safecrop-c426d.firebasestorage.app',
    measurementId: 'G-E1T9CGTQN5',
  );

}