// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudzuZkJCv93C4BLEGRQntFi-qHVGV-jA',
    appId: '1:814395547436:web:802e214b56aa7f7bfb9689',
    messagingSenderId: '814395547436',
    projectId: 'demow-7f680',
    authDomain: 'demow-7f680.firebaseapp.com',
    databaseURL: 'https://demow-7f680-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demow-7f680.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsjIg8YaDE9CLWgylk2bRGIEoDr7CSsc',
    appId: '1:814395547436:android:23e482d3142c3191fb9689',
    messagingSenderId: '814395547436',
    projectId: 'demow-7f680',
    databaseURL: 'https://demow-7f680-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demow-7f680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbo4SPbPjDwvGAgukkNkoHWBFzbzauxpo',
    appId: '1:814395547436:ios:89f741b73cf8d999fb9689',
    messagingSenderId: '814395547436',
    projectId: 'demow-7f680',
    databaseURL: 'https://demow-7f680-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demow-7f680.firebasestorage.app',
    iosBundleId: 'com.example.safecrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbo4SPbPjDwvGAgukkNkoHWBFzbzauxpo',
    appId: '1:814395547436:ios:89f741b73cf8d999fb9689',
    messagingSenderId: '814395547436',
    projectId: 'demow-7f680',
    databaseURL: 'https://demow-7f680-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demow-7f680.firebasestorage.app',
    iosBundleId: 'com.example.safecrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAudzuZkJCv93C4BLEGRQntFi-qHVGV-jA',
    appId: '1:814395547436:web:2a17349ba3f58b34fb9689',
    messagingSenderId: '814395547436',
    projectId: 'demow-7f680',
    authDomain: 'demow-7f680.firebaseapp.com',
    databaseURL: 'https://demow-7f680-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demow-7f680.firebasestorage.app',
  );
}
